
[Armor]
	#Enable Wither Upgraded Armor ?
	EnableWitherArmor = true
	#Enable Fire Upgraded Armor ?
	EnableFireArmor = true
	#Enable Water Upgraded Armor ?
	EnableWaterArmor = true
	#Enable Gold Upgraded Armor ?
	EnableGoldArmor = true
	#Enable Feather Upgraded Armor ?
	EnableFeatherArmor = true
	#Enable Phantom Upgraded Armor ?
	EnablePhantomArmor = true
	#Enable Ender Upgraded Armor ?
	EnableEnderArmor = true
	#Enable Poison Upgraded Armor ?
	EnablePoisonArmor = true
	#Enable Corrupt Upgraded Armor ?
	EnableCorruptArmor = true

	[Armor."Set Option"]
		#How many pieces of Phantom Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerPhantomArmorRequireSet = 4
		#How many pieces of Feather Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerFeatherArmorRequireSet = 4
		#How many pieces of Gold Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerGoldArmorRequireSet = 4
		#How many pieces of Ender Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerEnderArmorRequireSet = 4
		#How many pieces of Fire Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerFireArmorRequireSet = 4
		#How many pieces of Wither Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerWitherArmorRequireSet = 4
		#How many pieces of Water Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerWaterArmorRequireSet = 4
		#How many pieces of Poison Upgraded armor are needed to activate the effects?
		#Range: 1 ~ 4
		UpgradedPlayerPoisonArmorRequireSet = 4

["Horse Armor"]
	#Enable Feather Upgraded Armor Horse ?
	EnableFeatherArmorHorse = true
	#Enable Corrupt Upgraded Armor Horse ?
	EnableCorruptArmorHorse = true
	#Enable Ender Upgraded Armor Horse ?
	EnableEnderArmorHorse = true
	#Enable Poison Upgraded Armor Horse ?
	EnablePoisonArmorHorse = true
	#Enable Phantom Upgraded Armor Horse ?
	EnablePhantomArmorHorse = true
	#Enable Fire Upgraded Armor Horse ?
	EnableFireArmorHorse = true
	#Enable Wither Upgraded Armor Horse ?
	EnableWitherArmorHorse = true
	#Enable Gold Upgraded Armor Horse ?
	EnableGoldArmorHorse = true
	#Enable Water Upgraded Armor Horse ?
	EnableWaterArmorHorse = true

["Tool&Weapon"]
	#Enable Corrupt Upgraded Tool&Weapon ?
	EnableCorruptTool = true
	#Enable Water Upgraded Tool&Weapon ?
	EnableWaterTool = true
	#Enable Fire Upgraded Tool&Weapon ?
	EnableFireTool = true
	#Enable Ender Upgraded Tool&Weapon ?
	EnableEnderTool = true
	#Enable Wither Upgraded Tool&Weapon ?
	EnableWitherTool = true
	#Enable Gold Upgraded Tool&Weapon ?
	EnableGoldTool = true
	#Enable Poison Upgraded Tool&Weapon ?
	EnablePoisonTool = true
	#Enable Phantom Upgraded Tool&Weapon ?
	EnablePhantomTool = true
	#Enable Feather Upgraded Tool&Weapon ?
	EnableFeatherTool = true

[Shield]
	#Enable Corrupt Upgraded Shield ?
	EnableCorruptTool = true
	#Enable Water Upgraded Shield ?
	EnableWaterTool = true
	#Enable Fire Upgraded Shield ?
	EnableFireTool = true
	#Enable Ender Upgraded Shield ?
	EnableEnderTool = true
	#Enable Wither Upgraded Shield ?
	EnableWitherTool = true
	#Enable Gold Upgraded Shield ?
	EnableGoldTool = true
	#Enable Poison Upgraded Shield ?
	EnablePoisonTool = true
	#Enable Phantom Upgraded Shield ?
	EnablePhantomTool = true
	#Enable Feather Upgraded Shield ?
	EnableFeatherTool = true

[Effect]

	[Effect.Water]

		[Effect.Water.Armor]
			#Enable Water Upgraded Armor Effect : Mining Fatigue Immune ?(Only from the Elder Guardian and does not remove the effects already present)
			EnableElderGuardianDebuffImmune = true
			#Enable Water Upgraded Armor Effect : Water Speed ?
			EnableWaterSpeed = true
			#Enable Water Upgraded Armor Effect : Water Breathing ?
			EnableWaterBreath = true

			[Effect.Water.Armor.Durability]
				#How many durability damage take the Water Upgraded Armor when protect the player ? 
				#Range: 1 ~ 100
				DamageDurabilityWaterArmor = 1
				#Water Upgraded Armor loose durability when protect the player ? 
				EnableDamageDurabilityWaterArmor = false
				#How many tick between durability damage for the Water Upgraded Armor when it protect the player ? (20ticks = 1sec)
				#Range: 1 ~ 1000
				DelayDamageDurabilityWaterArmor = 20

		[Effect.Water."Tool&Weapon"]
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusWaterWeapon = 10
			#Enable Water Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusWaterWeapon = true
			#By how much are the damages against increased Enderman in percentage ?
			#Range: 1 ~ 999
			DamageBonusWaterEndermanWeapon = 10
			#Enable Water Upgraded Tool Effect : Increase Mining Speed underwater ?
			EnableMiningSpeedUnderwater = true
			#Enable Water Upgraded Weapon Effect : Increase against Enderman Damage ?
			EnableDamageBonusWaterEndermanWeapon = true

	[Effect.Wither]

		[Effect.Wither.Armor]
			#Enable Wither Upgraded Armor Effect : Wither Immune ?
			EnableWitherImmune = true

			[Effect.Wither.Armor.Durability]
				#How many durability damage take the Wither Upgraded Armor when protect the player ? 
				#Range: 1 ~ 100
				DamageDurabilityWitherArmor = 5
				#How many tick between durability damage for the Wither Upgraded Armor when it protect the player ? (20ticks = 1sec)
				#Range: 1 ~ 1000
				DelayDamageDurabilityWitherArmor = 20
				#Wither Upgraded Armor loose durability when protect the player ? 
				EnableDamageDurabilityWitherArmor = false

		[Effect.Wither."Tool&Weapon"]
			#Enable Wither Upgraded Weapon Effect : Wither Effect ?
			EnableWitherEffect = true
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusWitherWeapon = 4
			#Enable Wither Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusWitherWeapon = true

	[Effect.Gold]

		[Effect.Gold.Armor]
			#Enable Gold Upgraded Armor Effect : Increase Luck ?
			EnableLuckBonus = true
			#Enable Gold Upgraded Armor Effect : Piglin become neutral ?
			EnablePiglinNeutral = true
			#How much is the luck bonus increased ?
			#Range: 1 ~ 99
			LuckBonus = 2

		[Effect.Gold."Tool&Weapon"]
			#Enable Gold Upgraded Weapon Effect : Increase Looting ?
			EnableLootingBonus = true
			#Enable Gold Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusGoldWeapon = true
			#How much is the fortune bonus increased ?
			#Range: 1 ~ 99
			FortuneBonus = 1
			#How much is the looting bonus increased ?
			#Range: 1 ~ 99
			LootingBonus = 1
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusGoldWeapon = 10
			#How much is the looting bonus increased if enchanted ?
			#Range: 1 ~ 99
			LootingEnchantBonus = 1
			#How much is the fortune bonus increased if enchanted ?
			#Range: 1 ~ 99
			FortuneEnchantBonus = 1
			#Enable Gold Upgraded Weapon Effect : Increase Fortune ?
			EnableFortuneBonus = true

	[Effect.Fire]

		[Effect.Fire.Armor]
			#Enable Fire Upgraded Armor Effect : Fire damage immune ?
			EnableFireImmune = true
			#Enable Fire Upgraded Armor Effect : Lava Speed ?
			EnableLavaSpeed = true

			[Effect.Fire.Armor.Durability]
				#Fire Upgraded Armor loose durability when protect the player ? (Require EnableFireImmune = True)
				EnableDamageDurabilityFireArmor = false
				#How many tick between durability damage for the Fire Upgraded Armor when it protect the player ? (20ticks = 1sec)
				#Range: 1 ~ 1000
				DelayDamageDurabilityFireArmor = 20
				#How many durability damage take the Fire Upgraded Armor when protect the player ? 
				#Range: 1 ~ 100
				DamageDurabilityFireArmor = 1

		[Effect.Fire."Tool&Weapon"]
			#Auto-Smelt is affected by Fortune ? (Only Ingot & Charcoal)
			EnableAutoSmeltFortune = false
			#Enable Fire Upgraded Tool&Weapon Effect : Auto-Smelt ?
			EnableAutoSmelt = true
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusFireWeapon = 4
			#Enable Fire Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusFireWeapon = true
			#By how much are the damages increased in percentage if enchanted ?
			#Range: 1 ~ 999
			DamageBonusFireEnchantWeapon = 3

	[Effect.Ender]

		[Effect.Ender.Armor]
			#Enable Ender Upgraded Armor Effect : Prevent Enderman Anger ?
			EnablePreventAnger = true
			#Enable Ender Upgraded Armor Effect : Saves from the void ?
			EnableVoidSave = true

			[Effect.Ender.Armor.Durability]
				#Ender Upgraded Armor Break when save the player ? 
				EnableBreakEnderArmor = false

		[Effect.Ender."Tool&Weapon"]
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusEnderWeapon = 4
			#Enable Ender Upgraded Weapon Effect : Teleports Loot ?
			EnableTeleportChest = true
			#Enable Ender Upgraded Weapon Effect : Double Looting against Enderman ?
			EnableDoubleLootingBonusEnderWeapon = true
			#Enable Ender Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusEnderWeapon = true
			#Enable Ender Upgraded Weapon Effect : Prevent Teleport ?
			EnablePreventTeleport = true

	[Effect.Phantom]

		[Effect.Phantom.Armor]
			#Enable Phantom Upgraded Armor Effect : Step Height ?
			EnableStepHeight = true
			#Enable Phantom Upgraded Armor Effect : Fall damage Immune ?
			EnableFallImmune = true

			[Effect.Phantom.Armor.Durability]
				#Phantom Upgraded Armor loose durability when protect the player ? (Depend on fall distance)
				EnableDamageDurabilityPhantomArmor = false
				#How many durability damage take the Phantom Upgraded Armor when protect the player ? (Fall distance * Value)
				#Range: 1 ~ 100
				MultiplierDamageDurabilityPhantomArmor = 1

		[Effect.Phantom."Tool&Weapon"]
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusPhantomWeapon = 10
			#Enable Phantom Upgraded Tool Effect : Glowing Effect ?
			EnableGlowingEffect = true
			#Enable Phantom Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusPhantomWeapon = true
			#By how much are the reach increased ?
			#Range: 1 ~ 99
			BonusReachTool = 2
			#Enable Phantom Upgraded Tool Effect : Reach ?
			EnableReachEffect = true

	[Effect.Poison]

		[Effect.Poison.Armor]
			#Enable Poison Upgraded Armor Effect : Poison Immune ?
			EnablePoisonImmune = true
			#Enable Poison Upgraded Armor Effect : Climbs Walls ?
			EnableClimbWall = true

			[Effect.Poison.Armor.Durability]
				#Poison Upgraded Armor loose durability when protect the player ? 
				EnableDamageDurabilityPoisonArmor = false
				#How many tick between durability damage for the Poison Upgraded Armor when it protect the player ? (20ticks = 1sec)
				#Range: 1 ~ 1000
				DelayDamageDurabilityPoisonArmor = 20
				#How many durability damage take the Poison Upgraded Armor when protect the player ? 
				#Range: 1 ~ 100
				DamageDurabilityPoisonArmor = 5

		[Effect.Poison."Tool&Weapon"]
			#Enable Poison Upgraded Weapon Effect : Poison Effect ?
			EnablePoisonEffect = true
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusPoisonWeapon = 4
			#Enable Poison Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusPoisonWeapon = true

	[Effect.Feather]
		#Enable Feather Upgraded Tool Effect : Attracts Items ?
		EnableAttractItem = true

		[Effect.Feather.Armor]
			#Enable Feather Upgraded Armor Effect : Fall Damage Reduction ?
			EnableReduceFallDamage = true
			#Enable Feather Upgraded Armor Effect : Water & Lava Walking ?
			EnableWaterLavaWalking = true
			#How many Multi Jump ?
			#Range: 1 ~ 99
			MultiJump = 2
			#Enable Feather Upgraded Armor Effect : Multi Jump ?
			EnableMultiJump = true
			#Enable Feather Upgraded Armor Effect : Levitation Immune ?
			EnableLevitationImmune = true

			[Effect.Feather.Armor.Durability]
				#Feather Upgraded Armor loose durability when reducing fall damage ? 
				EnableFallDamageDurabilityFeatherArmor = false
				#How many durability damage take the Feather Upgraded Armor when the player walk on water/lava or slow falling ? 
				#Range: 1 ~ 100
				DamageDurabilityFeatherArmor = 1
				#Feather Upgraded Armor loose durability when the player walk on water ? 
				EnableWaterDamageDurabilityFeatherArmor = false
				#How many tick between durability damage for the Feather Upgraded Armor when the player walk on water/lava or slow falling ? (20ticks = 1sec)
				#Range: 1 ~ 1000
				DelayDamageDurabilityFeatherArmor = 20
				#Feather Upgraded Armor loose durability when the player walk on lava ? 
				EnableLavaDamageDurabilityFeatherArmor = false

	[Effect.Corrupt]

		[Effect.Corrupt.Armor]
			#By how much are the health reduced in percentage ?
			#Range: 1 ~ 99
			HealthMalus = 10
			#Enable Corrupt Upgraded Armor Effect : Health Malus ?
			EnableHealthMalus = true

		[Effect.Corrupt."Tool&Weapon"]
			#Enable Corrupt Upgraded Weapon Effect : Increase Damage ?
			EnableDamageBonusCorruptWeapon = true
			#Enable Gold Upgraded Weapon Effect : Increase Fortune ?
			EnableFortuneBonusCorruptTool = true
			#Enable Corrupt Upgraded Weapon Effect : Increase Looting ?
			EnableLootingBonusCorruptWeapon = true
			#How much is the fortune bonus increased ?
			#Range: 1 ~ 99
			FortuneBonusCorruptTool = 2
			#How much is the looting bonus increased ?
			#Range: 1 ~ 99
			LootingBonusCorruptWeapon = 2
			#By how much are the damages increased in percentage ?
			#Range: 1 ~ 999
			DamageBonusCorruptWeapon = 7

